apiVersion: v1
data:
  autoexec.cfg: |+
    # sample mysql ddnet server config

    sv_name "[k8s] BanBansNet GER 1"
    sv_map "ChillDontKill"

    password test

    sv_use_sql 1
    # add_sqlserver s['r'|'w'] s[Database] s[Prefix] s[User] s[Password] s[IP] i[Port] ?i[SetUpDatabase ?]
    add_sqlserver r bbnet record root secret mariadb 3306
    add_sqlserver w bbnet record root secret mariadb 3306

kind: ConfigMap
metadata:
  name: ddnet-autoexec
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maps-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-maps
spec:
  template:
    spec:
      containers:
      - name: get-maps
        image: busybox:latest
        command: ["sh", "-c"]
        args:
         - wget -O maps.zip
           "https://github.com/BanBansNet/bbnet-maps/archive/refs/heads/master.zip";
           unzip maps.zip;
           mv bbnet-maps-master/*.map /ddnet/maps/
        volumeMounts:
        - name: maps
          mountPath: /ddnet/maps
      volumes:
        - name: maps
          persistentVolumeClaim:
            claimName: maps-pvc
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddnet-deployment
  labels:
    app: ddnet
spec:
  selector:
    matchLabels:
      app: ddnet
  template:
    metadata:
      labels:
        app: ddnet
    spec:
      containers:
      - name: ddnet
        image: chillerdragon/ddnet-mysql:17.1
        command: ["/ddnet/DDNet-Server", "-f", "/ddnet/config/autoexec.cfg"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8303
          protocol: UDP
          hostPort: 8305
        volumeMounts:
          - name: config-volume
            mountPath: /ddnet/config
          - name: maps
            mountPath: /ddnet/maps
      initContainers:
      - name: wait-for-maps
        image: busybox:latest
        command: ["sh", "-c"]
        args:
         - while [ ! -f /ddnet/maps/ChillDontKill.map ];
           do
             sleep 1;
             echo "waiting for maps ...";
           done
        volumeMounts:
        - name: maps
          mountPath: /ddnet/maps
      volumes:
        - name: config-volume
          configMap:
            name: ddnet-autoexec
            items:
            - key: autoexec.cfg
              path: autoexec.cfg
        - name: maps
          persistentVolumeClaim:
            claimName: maps-pvc
