apiVersion: v1
kind: Pod
metadata:
  name: ddnet
spec:
  containers:
  - name: ddnet
    image: chillerdragon/ddnet-simple:17.0.3
    ports:
    - containerPort: 8303
      protocol: UDP
      hostPort: 8304

